language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y -qq gcc-avr binutils-avr avr-libc
script:
  - make all CONFIG=DEBUG
  - make all CONFIG=RELEASE
notifications:
  email:
    on_success: change
    on_failure: change
